import type { TipoCalendario } from "./calendario";

/* ────────────────────────────────────────────────────────────────────────────
 * Catálogo de términos. Cada entrada declara su norma, su URL oficial y su
 * ESTADO DE VERIFICACIÓN con fecha:
 *   VERIFICADA   · fuente oficial consultada en la fecha indicada
 *   CONTRASTADA  · texto transcrito de fuente oficial en documentación del proyecto
 *   PENDIENTE    · debe confirmarse en fuente oficial antes de sustentar una actuación
 * El Módulo 4 intenta verificar en tiempo de ejecución (Croma / fuente oficial)
 * y el Módulo 21 impide que un término PENDIENTE entre sin advertencia visible.
 * Ningún término de este catálogo sustituye el cómputo del ABOGADO (USUARIO).
 * ──────────────────────────────────────────────────────────────────────────── */

export type TipoTerminoCatalogo = "PRESCRIPCION" | "CADUCIDAD" | "PROCESAL" | "DESISTIMIENTO_TACITO" | "RESPUESTA_AUTORIDAD" | "NOTIFICACION" | "INMEDIATEZ";
export type UnidadCatalogo = "DIAS_HABILES" | "DIAS_CALENDARIO" | "MESES" | "ANIOS" | "SIN_TERMINO";

export interface EntradaTermino {
  id: string;
  nombre: string;
  tipo: TipoTerminoCatalogo;
  areas: string[];
  unidad: UnidadCatalogo;
  cantidad: number;
  inicio: string;
  inicioCuenta: "DIA_SIGUIENTE" | "MISMO_DIA";
  calendario: TipoCalendario;
  norma: string;
  url: string | null;
  verificacion: string;
  seAlega?: boolean;
  deOficio?: boolean;
  interrupcion?: string;
  suspension?: string;
  notas?: string[];
}

const SENADO = "http://www.secretariasenado.gov.co/senado/basedoc";
const CGP = `${SENADO}/ley_1564_2012.html`;
const CPACA = `${SENADO}/ley_1437_2011.html`;

export const CATALOGO_TERMINOS: EntradaTermino[] = [
  // ─── Prescripción civil y comercial
  { id: "civil_ordinaria", nombre: "Prescripción extintiva de la acción ordinaria", tipo: "PRESCRIPCION", areas: ["CIVIL", "COMERCIAL", "FAMILIA"], unidad: "ANIOS", cantidad: 10, inicio: "Exigibilidad de la obligación (art. 2535 C.C.)", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Código Civil, art. 2536, modificado por la Ley 791 de 2002, art. 8", url: `${SENADO}/codigo_civil.html`, verificacion: "VERIFICADA 2026-09-22 (Función Pública, Ley 791 de 2002)", seAlega: true, interrupcion: "Natural (reconocimiento del deudor) o civil (demanda notificada en término, art. 94 CGP).", suspension: "A favor de incapaces y demás personas del art. 2530 C.C." },
  { id: "civil_ejecutiva", nombre: "Prescripción de la acción ejecutiva", tipo: "PRESCRIPCION", areas: ["CIVIL", "COMERCIAL", "FAMILIA"], unidad: "ANIOS", cantidad: 5, inicio: "Exigibilidad del título", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Código Civil, art. 2536, modificado por la Ley 791 de 2002, art. 8", url: `${SENADO}/codigo_civil.html`, verificacion: "VERIFICADA 2026-09-22", seAlega: true, notas: ["Vencidos los cinco años, la acción ejecutiva pasa a ser ordinaria y esta prescribe en otros cinco (art. 2536 C.C.).", "Cada cuota periódica (p. ej. alimentos) prescribe de forma independiente desde su exigibilidad."] },
  { id: "cambiaria_directa", nombre: "Prescripción de la acción cambiaria directa", tipo: "PRESCRIPCION", areas: ["COMERCIAL"], unidad: "ANIOS", cantidad: 3, inicio: "Fecha del vencimiento del título", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Código de Comercio, art. 789", url: `${SENADO}/codigo_comercio.html`, verificacion: "PENDIENTE de verificación en fuente oficial", seAlega: true, notas: ["Si la fecha de pago coincide con la de creación, el título nace vencido y el término corre desde esa fecha."] },
  { id: "cambiaria_regreso", nombre: "Caducidad/prescripción de la acción cambiaria de regreso", tipo: "PRESCRIPCION", areas: ["COMERCIAL"], unidad: "ANIOS", cantidad: 1, inicio: "Fecha del protesto o del vencimiento, según el caso", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Código de Comercio, art. 790", url: `${SENADO}/codigo_comercio.html`, verificacion: "PENDIENTE de verificación en fuente oficial", seAlega: true },
  { id: "seguro_ordinaria", nombre: "Prescripción ordinaria del contrato de seguro", tipo: "PRESCRIPCION", areas: ["COMERCIAL", "CONSUMIDOR"], unidad: "ANIOS", cantidad: 2, inicio: "Conocimiento real o presunto del hecho que da base a la acción", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Código de Comercio, art. 1081", url: `${SENADO}/codigo_comercio.html`, verificacion: "VERIFICADA 2026-09-22 (SFC y CSJ)", seAlega: true, notas: ["Seguro de responsabilidad civil (art. 1131 C.Co.): para el asegurado, el término se cuenta desde que la víctima le reclama; para la acción directa de la víctima, desde el siniestro."] },
  { id: "seguro_extraordinaria", nombre: "Prescripción extraordinaria del contrato de seguro", tipo: "PRESCRIPCION", areas: ["COMERCIAL", "CONSUMIDOR"], unidad: "ANIOS", cantidad: 5, inicio: "Nacimiento del derecho (corre contra toda persona)", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Código de Comercio, art. 1081", url: `${SENADO}/codigo_comercio.html`, verificacion: "VERIFICADA 2026-09-22", seAlega: true, notas: ["Los términos del art. 1081 no pueden modificarse por las partes."] },
  { id: "competencia_desleal_subjetiva", nombre: "Prescripción de la acción de competencia desleal (subjetiva)", tipo: "PRESCRIPCION", areas: ["COMERCIAL"], unidad: "ANIOS", cantidad: 2, inicio: "Conocimiento de la persona que realizó el acto", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Ley 256 de 1996, art. 23", url: `${SENADO}/ley_0256_1996.html`, verificacion: "VERIFICADA 2026-09-22", seAlega: true },
  { id: "competencia_desleal_objetiva", nombre: "Prescripción de la acción de competencia desleal (objetiva)", tipo: "PRESCRIPCION", areas: ["COMERCIAL"], unidad: "ANIOS", cantidad: 3, inicio: "Realización del acto", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Ley 256 de 1996, art. 23", url: `${SENADO}/ley_0256_1996.html`, verificacion: "VERIFICADA 2026-09-22", seAlega: true },
  { id: "agencia_comercial", nombre: "Prescripción de acciones del contrato de agencia comercial", tipo: "PRESCRIPCION", areas: ["COMERCIAL"], unidad: "ANIOS", cantidad: 5, inicio: "Terminación del contrato", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Código de Comercio, art. 1329", url: `${SENADO}/codigo_comercio.html`, verificacion: "PENDIENTE: confirmar texto (CSJ SC3085-2017 lo aplica)", seAlega: true },
  { id: "transporte", nombre: "Prescripción de acciones del contrato de transporte", tipo: "PRESCRIPCION", areas: ["COMERCIAL"], unidad: "ANIOS", cantidad: 2, inicio: "Según la norma especial", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Código de Comercio, art. 993", url: `${SENADO}/codigo_comercio.html`, verificacion: "PENDIENTE de verificación en fuente oficial", seAlega: true },
  { id: "nulidad_relativa", nombre: "Rescisión por nulidad relativa", tipo: "PRESCRIPCION", areas: ["CIVIL", "COMERCIAL"], unidad: "ANIOS", cantidad: 4, inicio: "Celebración del acto o cese de la causa (violencia, incapacidad), según el caso", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Código Civil, art. 1750", url: `${SENADO}/codigo_civil.html`, verificacion: "PENDIENTE de verificación en fuente oficial", seAlega: true },
  { id: "lesion_enorme", nombre: "Rescisión por lesión enorme", tipo: "PRESCRIPCION", areas: ["CIVIL"], unidad: "ANIOS", cantidad: 4, inicio: "Fecha del contrato", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Código Civil, art. 1954", url: `${SENADO}/codigo_civil.html`, verificacion: "PENDIENTE de verificación en fuente oficial", seAlega: true },
  { id: "accion_pauliana", nombre: "Acción revocatoria (pauliana)", tipo: "PRESCRIPCION", areas: ["CIVIL", "INSOLVENCIA"], unidad: "ANIOS", cantidad: 1, inicio: "Fecha del acto o contrato", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Código Civil, art. 2491", url: `${SENADO}/codigo_civil.html`, verificacion: "PENDIENTE de verificación en fuente oficial", seAlega: true },
  // ─── Laboral
  { id: "laboral_general", nombre: "Prescripción de acciones laborales", tipo: "PRESCRIPCION", areas: ["LABORAL", "SEGURIDAD_SOCIAL"], unidad: "ANIOS", cantidad: 3, inicio: "Exigibilidad de cada derecho", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Código Sustantivo del Trabajo, arts. 488 y 489; Código Procesal del Trabajo y de la Seguridad Social, art. 151", url: `${SENADO}/codigo_sustantivo_trabajo.html`, verificacion: "PENDIENTE de verificación en fuente oficial", seAlega: true, interrupcion: "Simple reclamo escrito del trabajador recibido por el empleador, por una sola vez y por un lapso igual." },
  // ─── Consumo y servicios públicos
  { id: "consumidor_garantia", nombre: "Acción de protección al consumidor (garantía)", tipo: "PRESCRIPCION", areas: ["CONSUMIDOR"], unidad: "ANIOS", cantidad: 1, inicio: "Expiración de la garantía", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Ley 1480 de 2011, art. 58, num. 3", url: `${SENADO}/ley_1480_2011.html`, verificacion: "VERIFICADA 2026-09-22", notas: ["Hay que acreditar que se reclamó mientras la garantía estaba vigente. Por favorabilidad (art. 4 Ley 1480), la SIC lo aplica como término de prescripción."] },
  { id: "consumidor_contractual", nombre: "Acción de protección al consumidor (controversias contractuales)", tipo: "PRESCRIPCION", areas: ["CONSUMIDOR"], unidad: "ANIOS", cantidad: 1, inicio: "Terminación del contrato", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Ley 1480 de 2011, art. 58, num. 3", url: `${SENADO}/ley_1480_2011.html`, verificacion: "VERIFICADA 2026-09-22" },
  { id: "consumidor_otros", nombre: "Acción de protección al consumidor (demás casos)", tipo: "PRESCRIPCION", areas: ["CONSUMIDOR"], unidad: "ANIOS", cantidad: 1, inicio: "Conocimiento de los hechos que motivaron la reclamación", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Ley 1480 de 2011, art. 58, num. 3", url: `${SENADO}/ley_1480_2011.html`, verificacion: "VERIFICADA 2026-09-22" },
  { id: "spd_reclamacion_factura", nombre: "Reclamación contra factura de servicios públicos", tipo: "CADUCIDAD", areas: ["SERVICIOS_PUBLICOS"], unidad: "MESES", cantidad: 5, inicio: "Expedición de la factura", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Ley 142 de 1994, art. 154, inc. 3", url: `${SENADO}/ley_0142_1994.html`, verificacion: "VERIFICADA 2026-09-22 (Secretaría del Senado)", deOficio: true },
  { id: "spd_cobro_inoportuno", nombre: "Límite para cobrar lo no facturado (empresa)", tipo: "CADUCIDAD", areas: ["SERVICIOS_PUBLICOS"], unidad: "MESES", cantidad: 5, inicio: "Entrega de la factura del período", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Ley 142 de 1994, art. 150", url: `${SENADO}/ley_0142_1994.html`, verificacion: "VERIFICADA 2026-09-22", notas: ["Excepción: dolo comprobado del suscriptor o usuario."] },
  { id: "spd_recurso", nombre: "Recurso de reposición y subsidiario de apelación ante la prestadora", tipo: "PROCESAL", areas: ["SERVICIOS_PUBLICOS"], unidad: "DIAS_HABILES", cantidad: 5, inicio: "Notificación de la decisión de la empresa", inicioCuenta: "DIA_SIGUIENTE", calendario: "ADMINISTRATIVO", norma: "Ley 142 de 1994, arts. 154 y 159", url: `${SENADO}/ley_0142_1994.html`, verificacion: "VERIFICADA 2026-09-22", notas: ["Sin abogado ni presentación personal; la apelación solo como subsidiaria ante la Superservicios."] },
  { id: "spd_respuesta", nombre: "Respuesta de la prestadora a peticiones, quejas y recursos", tipo: "RESPUESTA_AUTORIDAD", areas: ["SERVICIOS_PUBLICOS"], unidad: "DIAS_HABILES", cantidad: 15, inicio: "Recepción de la petición o recurso", inicioCuenta: "DIA_SIGUIENTE", calendario: "ADMINISTRATIVO", norma: "Ley 142 de 1994, art. 158 (subrogado por el Decreto 2150 de 1995)", url: `${SENADO}/ley_0142_1994.html`, verificacion: "VERIFICADA 2026-09-22", notas: ["Vencido sin respuesta opera el silencio administrativo positivo, que la empresa debe reconocer en 72 horas."] },
  // ─── Contencioso administrativo (CPACA art. 164)
  { id: "cpaca_nulidad_restablecimiento", nombre: "Caducidad del medio de control de nulidad y restablecimiento del derecho", tipo: "CADUCIDAD", areas: ["ADMINISTRATIVO"], unidad: "MESES", cantidad: 4, inicio: "Día siguiente a la comunicación, notificación, ejecución o publicación del acto", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Ley 1437 de 2011 (CPACA), art. 164, num. 2, lit. d", url: CPACA, verificacion: "PENDIENTE de verificación en fuente oficial", deOficio: true, suspension: "La solicitud de conciliación extrajudicial suspende el término (Ley 2220 de 2022; verificar artículo y límite).", notas: ["Contra actos producto del silencio administrativo negativo la demanda puede presentarse en cualquier tiempo (art. 164, num. 1, lit. d)."] },
  { id: "cpaca_reparacion_directa", nombre: "Caducidad del medio de control de reparación directa", tipo: "CADUCIDAD", areas: ["ADMINISTRATIVO"], unidad: "ANIOS", cantidad: 2, inicio: "Día siguiente a la ocurrencia de la acción u omisión causante del daño, o al conocimiento si fue posterior", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Ley 1437 de 2011 (CPACA), art. 164, num. 2, lit. i", url: CPACA, verificacion: "PENDIENTE de verificación en fuente oficial", deOficio: true, notas: ["Reglas jurisprudenciales de modulación: daño que se consolida después, conocimiento tardío de la participación estatal, violaciones de derechos humanos y lesa humanidad."] },
  { id: "cpaca_controversias_contractuales", nombre: "Caducidad del medio de control de controversias contractuales", tipo: "CADUCIDAD", areas: ["ADMINISTRATIVO", "CONTRATACION_ESTATAL"], unidad: "ANIOS", cantidad: 2, inicio: "Según el literal aplicable (ocurrencia de los motivos, liquidación o vencimiento del plazo para liquidar)", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Ley 1437 de 2011 (CPACA), art. 164, num. 2, lit. j", url: CPACA, verificacion: "PENDIENTE de verificación en fuente oficial", deOficio: true },
  { id: "cpaca_nulidad_electoral", nombre: "Caducidad del medio de control de nulidad electoral", tipo: "CADUCIDAD", areas: ["ADMINISTRATIVO"], unidad: "DIAS_HABILES", cantidad: 30, inicio: "Día siguiente a la declaración de la elección o a la publicación del nombramiento", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Ley 1437 de 2011 (CPACA), art. 164, num. 2, lit. a", url: CPACA, verificacion: "PENDIENTE de verificación en fuente oficial", deOficio: true },
  { id: "cpaca_repeticion", nombre: "Caducidad del medio de control de repetición", tipo: "CADUCIDAD", areas: ["ADMINISTRATIVO"], unidad: "ANIOS", cantidad: 2, inicio: "Día siguiente al pago o al vencimiento del plazo para pagar", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Ley 1437 de 2011 (CPACA), art. 164, num. 2, lit. l", url: CPACA, verificacion: "PENDIENTE de verificación en fuente oficial", deOficio: true },
  { id: "cpaca_nulidad_simple", nombre: "Medio de control de nulidad simple", tipo: "CADUCIDAD", areas: ["ADMINISTRATIVO"], unidad: "SIN_TERMINO", cantidad: 0, inicio: "En cualquier tiempo", inicioCuenta: "MISMO_DIA", calendario: "JUDICIAL", norma: "Ley 1437 de 2011 (CPACA), art. 164, num. 1, lit. a", url: CPACA, verificacion: "PENDIENTE de verificación en fuente oficial" },
  { id: "accion_grupo", nombre: "Caducidad de la acción de grupo (reparación de perjuicios a un grupo)", tipo: "CADUCIDAD", areas: ["CONSTITUCIONAL", "ADMINISTRATIVO", "CIVIL"], unidad: "ANIOS", cantidad: 2, inicio: "Fecha en que se causó el daño o cesó la acción vulnerante", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Ley 472 de 1998, art. 47", url: `${SENADO}/ley_0472_1998.html`, verificacion: "PENDIENTE de verificación en fuente oficial", deOficio: true },
  { id: "accion_popular", nombre: "Acción popular", tipo: "CADUCIDAD", areas: ["CONSTITUCIONAL"], unidad: "SIN_TERMINO", cantidad: 0, inicio: "Mientras subsista la amenaza o el peligro al derecho colectivo", inicioCuenta: "MISMO_DIA", calendario: "JUDICIAL", norma: "Ley 472 de 1998, art. 11", url: `${SENADO}/ley_0472_1998.html`, verificacion: "PENDIENTE de verificación en fuente oficial" },
  // ─── Tutela
  { id: "tutela_inmediatez", nombre: "Inmediatez de la acción de tutela (plazo razonable)", tipo: "INMEDIATEZ", areas: ["CONSTITUCIONAL"], unidad: "MESES", cantidad: 6, inicio: "Hecho vulnerador o su último acto", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Decreto 2591 de 1991 y jurisprudencia constitucional sobre inmediatez (plazo razonable, sin término de caducidad legal)", url: `${SENADO}/decreto_2591_1991.html`, verificacion: "PENDIENTE: referencia jurisprudencial orientativa, no es término legal", notas: ["La tutela no tiene término de caducidad; seis meses es solo una referencia orientativa de razonabilidad que admite justificación de la demora.", "Vulneraciones continuadas o sujetos de especial protección flexibilizan el análisis."] },
  { id: "tutela_fallo", nombre: "Término para fallar la tutela en primera instancia", tipo: "RESPUESTA_AUTORIDAD", areas: ["CONSTITUCIONAL"], unidad: "DIAS_HABILES", cantidad: 10, inicio: "Presentación de la solicitud", inicioCuenta: "DIA_SIGUIENTE", calendario: "ADMINISTRATIVO", norma: "Decreto 2591 de 1991, art. 29", url: `${SENADO}/decreto_2591_1991.html`, verificacion: "PENDIENTE de verificación en fuente oficial", notas: ["La tutela no se suspende en vacancia judicial: por eso se usa calendario sin vacancia."] },
  { id: "tutela_impugnacion", nombre: "Impugnación del fallo de tutela", tipo: "PROCESAL", areas: ["CONSTITUCIONAL"], unidad: "DIAS_HABILES", cantidad: 3, inicio: "Notificación del fallo", inicioCuenta: "DIA_SIGUIENTE", calendario: "ADMINISTRATIVO", norma: "Decreto 2591 de 1991, art. 31", url: `${SENADO}/decreto_2591_1991.html`, verificacion: "PENDIENTE de verificación en fuente oficial" },
  // ─── Derecho de petición y vía administrativa
  { id: "peticion_general", nombre: "Respuesta a derecho de petición (regla general)", tipo: "RESPUESTA_AUTORIDAD", areas: ["ADMINISTRATIVO", "CONSTITUCIONAL", "CONSUMIDOR", "SERVICIOS_PUBLICOS"], unidad: "DIAS_HABILES", cantidad: 15, inicio: "Recepción de la petición", inicioCuenta: "DIA_SIGUIENTE", calendario: "ADMINISTRATIVO", norma: "Ley 1437 de 2011, art. 14, sustituido por la Ley 1755 de 2015", url: `${SENADO}/ley_1755_2015.html`, verificacion: "CONTRASTADA (Ley 1755 de 2015, Secretaría del Senado)" },
  { id: "peticion_documentos", nombre: "Respuesta a petición de documentos e información", tipo: "RESPUESTA_AUTORIDAD", areas: ["ADMINISTRATIVO", "CONSTITUCIONAL"], unidad: "DIAS_HABILES", cantidad: 10, inicio: "Recepción de la petición", inicioCuenta: "DIA_SIGUIENTE", calendario: "ADMINISTRATIVO", norma: "Ley 1437 de 2011, art. 14, num. 1, sustituido por la Ley 1755 de 2015", url: `${SENADO}/ley_1755_2015.html`, verificacion: "CONTRASTADA (Ley 1755 de 2015)", notas: ["Vencido el término sin respuesta, se entiende aceptada la solicitud y deben entregarse las copias dentro de los tres días siguientes."] },
  { id: "peticion_consulta", nombre: "Respuesta a petición de consulta", tipo: "RESPUESTA_AUTORIDAD", areas: ["ADMINISTRATIVO", "TRIBUTARIO"], unidad: "DIAS_HABILES", cantidad: 30, inicio: "Recepción de la consulta", inicioCuenta: "DIA_SIGUIENTE", calendario: "ADMINISTRATIVO", norma: "Ley 1437 de 2011, art. 14, num. 2, sustituido por la Ley 1755 de 2015", url: `${SENADO}/ley_1755_2015.html`, verificacion: "CONTRASTADA (Ley 1755 de 2015)" },
  { id: "cpaca_recursos", nombre: "Recursos de reposición y apelación en vía administrativa", tipo: "PROCESAL", areas: ["ADMINISTRATIVO", "TRIBUTARIO"], unidad: "DIAS_HABILES", cantidad: 10, inicio: "Notificación personal, por aviso o vencimiento del término de publicación", inicioCuenta: "DIA_SIGUIENTE", calendario: "ADMINISTRATIVO", norma: "Ley 1437 de 2011 (CPACA), art. 76", url: CPACA, verificacion: "PENDIENTE de verificación en fuente oficial", notas: ["El de apelación es obligatorio para acudir a la jurisdicción (art. 161, num. 2); el de reposición no."] },
  { id: "cpaca_silencio_negativo", nombre: "Silencio administrativo negativo", tipo: "RESPUESTA_AUTORIDAD", areas: ["ADMINISTRATIVO"], unidad: "MESES", cantidad: 3, inicio: "Presentación de la petición", inicioCuenta: "DIA_SIGUIENTE", calendario: "ADMINISTRATIVO", norma: "Ley 1437 de 2011 (CPACA), art. 83", url: CPACA, verificacion: "PENDIENTE de verificación en fuente oficial" },
  { id: "accion_cumplimiento_renuencia", nombre: "Constitución en renuencia para la acción de cumplimiento", tipo: "RESPUESTA_AUTORIDAD", areas: ["CONSTITUCIONAL", "ADMINISTRATIVO"], unidad: "DIAS_HABILES", cantidad: 10, inicio: "Radicación de la reclamación de cumplimiento", inicioCuenta: "DIA_SIGUIENTE", calendario: "ADMINISTRATIVO", norma: "Ley 393 de 1997, art. 8", url: `${SENADO}/ley_0393_1997.html`, verificacion: "CONTRASTADA (Ley 393 de 1997)" },
  { id: "accion_popular_requerimiento", nombre: "Requerimiento previo a la autoridad (acción popular)", tipo: "RESPUESTA_AUTORIDAD", areas: ["CONSTITUCIONAL", "ADMINISTRATIVO"], unidad: "DIAS_HABILES", cantidad: 15, inicio: "Radicación de la solicitud de adopción de medidas", inicioCuenta: "DIA_SIGUIENTE", calendario: "ADMINISTRATIVO", norma: "Ley 1437 de 2011 (CPACA), art. 144, inc. 3", url: CPACA, verificacion: "PENDIENTE de verificación en fuente oficial", notas: ["Excepción: inminente peligro de ocurrir un perjuicio irremediable."] },
  // ─── Procesales CGP
  { id: "cgp_reposicion", nombre: "Recurso de reposición contra auto proferido fuera de audiencia", tipo: "PROCESAL", areas: ["CIVIL", "COMERCIAL", "FAMILIA", "LABORAL"], unidad: "DIAS_HABILES", cantidad: 3, inicio: "Notificación del auto", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Ley 1564 de 2012 (CGP), art. 318", url: CGP, verificacion: "PENDIENTE de verificación en fuente oficial" },
  { id: "cgp_apelacion", nombre: "Interposición del recurso de apelación contra providencia fuera de audiencia", tipo: "PROCESAL", areas: ["CIVIL", "COMERCIAL", "FAMILIA"], unidad: "DIAS_HABILES", cantidad: 3, inicio: "Notificación de la providencia", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Ley 1564 de 2012 (CGP), art. 322, num. 1", url: CGP, verificacion: "PENDIENTE de verificación en fuente oficial" },
  { id: "cgp_ejecutoria", nombre: "Ejecutoria de providencias proferidas fuera de audiencia", tipo: "PROCESAL", areas: ["CIVIL", "COMERCIAL", "FAMILIA"], unidad: "DIAS_HABILES", cantidad: 3, inicio: "Notificación de la providencia", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Ley 1564 de 2012 (CGP), art. 302", url: CGP, verificacion: "PENDIENTE de verificación en fuente oficial" },
  { id: "cgp_subsanar", nombre: "Subsanación de la demanda inadmitida", tipo: "PROCESAL", areas: ["CIVIL", "COMERCIAL", "FAMILIA"], unidad: "DIAS_HABILES", cantidad: 5, inicio: "Notificación del auto inadmisorio", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Ley 1564 de 2012 (CGP), art. 90", url: CGP, verificacion: "PENDIENTE de verificación en fuente oficial" },
  { id: "cgp_traslado_verbal", nombre: "Traslado de la demanda en proceso verbal", tipo: "PROCESAL", areas: ["CIVIL", "COMERCIAL", "FAMILIA"], unidad: "DIAS_HABILES", cantidad: 20, inicio: "Notificación del auto admisorio al demandado", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Ley 1564 de 2012 (CGP), art. 369", url: CGP, verificacion: "PENDIENTE de verificación en fuente oficial" },
  { id: "cgp_traslado_verbal_sumario", nombre: "Traslado de la demanda en proceso verbal sumario", tipo: "PROCESAL", areas: ["CIVIL", "COMERCIAL", "FAMILIA"], unidad: "DIAS_HABILES", cantidad: 10, inicio: "Notificación del auto admisorio al demandado", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Ley 1564 de 2012 (CGP), art. 391", url: CGP, verificacion: "PENDIENTE de verificación en fuente oficial" },
  { id: "cgp_pago_ejecutivo", nombre: "Pago ordenado en el mandamiento ejecutivo", tipo: "PROCESAL", areas: ["CIVIL", "COMERCIAL", "FAMILIA"], unidad: "DIAS_HABILES", cantidad: 5, inicio: "Notificación del mandamiento de pago", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Ley 1564 de 2012 (CGP), art. 431", url: CGP, verificacion: "PENDIENTE de verificación en fuente oficial" },
  { id: "cgp_reposicion_mandamiento", nombre: "Reposición contra el mandamiento de pago (hechos de excepciones previas y requisitos formales del título)", tipo: "PROCESAL", areas: ["CIVIL", "COMERCIAL", "FAMILIA"], unidad: "DIAS_HABILES", cantidad: 3, inicio: "Notificación del mandamiento de pago", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Ley 1564 de 2012 (CGP), arts. 318, 430 y 442, num. 3", url: CGP, verificacion: "PENDIENTE de verificación en fuente oficial" },
  { id: "cgp_excepciones_ejecutivo", nombre: "Proposición de excepciones de mérito en el proceso ejecutivo", tipo: "PROCESAL", areas: ["CIVIL", "COMERCIAL", "FAMILIA"], unidad: "DIAS_HABILES", cantidad: 10, inicio: "Notificación del mandamiento de pago", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Ley 1564 de 2012 (CGP), art. 442, num. 1", url: CGP, verificacion: "PENDIENTE de verificación en fuente oficial" },
  { id: "cgp_notificacion_demandado_1_anio", nombre: "Notificación al demandado para que la demanda interrumpa la prescripción", tipo: "PROCESAL", areas: ["CIVIL", "COMERCIAL", "FAMILIA", "LABORAL"], unidad: "ANIOS", cantidad: 1, inicio: "Día siguiente a la notificación al demandante del auto admisorio o del mandamiento ejecutivo", inicioCuenta: "DIA_SIGUIENTE", calendario: "CALENDARIO", norma: "Ley 1564 de 2012 (CGP), art. 94", url: "https://procesal.uexternado.edu.co/codigo-general/articulo-94-interrupcion-de-la-prescripcion-inoperancia-de-la-caducidad-y-constitucion-en-mora/", verificacion: "CONTRASTADA (texto transcrito del art. 94 CGP)", notas: ["Vencido el año, la interrupción solo se produce con la notificación efectiva al demandado."] },
  { id: "cgp_desistimiento_tacito_carga", nombre: "Desistimiento tácito por incumplimiento de carga ordenada", tipo: "DESISTIMIENTO_TACITO", areas: ["CIVIL", "COMERCIAL", "FAMILIA"], unidad: "DIAS_HABILES", cantidad: 30, inicio: "Notificación del auto que ordena cumplir la carga", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Ley 1564 de 2012 (CGP), art. 317, num. 1", url: `${SENADO}/ley_1564_2012_pr010.html`, verificacion: "CONTRASTADA (art. 317 CGP, Secretaría del Senado)" },
  { id: "cgp_desistimiento_tacito_inactividad", nombre: "Desistimiento tácito por inactividad en secretaría", tipo: "DESISTIMIENTO_TACITO", areas: ["CIVIL", "COMERCIAL", "FAMILIA"], unidad: "ANIOS", cantidad: 1, inicio: "Día siguiente a la última notificación o a la última diligencia o actuación", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Ley 1564 de 2012 (CGP), art. 317, num. 2", url: `${SENADO}/ley_1564_2012_pr010.html`, verificacion: "CONTRASTADA (art. 317 CGP, Secretaría del Senado)", notas: ["Con sentencia ejecutoriada a favor del demandante o auto que ordena seguir adelante la ejecución, el plazo es de dos años.", "Una segunda declaración entre las mismas partes extingue el derecho pretendido."] },
  { id: "cgp_desistimiento_tacito_inactividad_sentencia", nombre: "Desistimiento tácito por inactividad con sentencia o auto de seguir adelante la ejecución", tipo: "DESISTIMIENTO_TACITO", areas: ["CIVIL", "COMERCIAL", "FAMILIA"], unidad: "ANIOS", cantidad: 2, inicio: "Día siguiente a la última notificación o a la última diligencia o actuación", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Ley 1564 de 2012 (CGP), art. 317, num. 2, lit. b", url: `${SENADO}/ley_1564_2012_pr010.html`, verificacion: "PENDIENTE de verificación en fuente oficial" },
  { id: "cgp_aviso", nombre: "Notificación por aviso (perfeccionamiento)", tipo: "NOTIFICACION", areas: ["CIVIL", "COMERCIAL", "FAMILIA", "LABORAL"], unidad: "DIAS_HABILES", cantidad: 1, inicio: "Entrega del aviso en el lugar de destino", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Ley 1564 de 2012 (CGP), art. 292", url: CGP, verificacion: "PENDIENTE de verificación en fuente oficial", notas: ["La notificación se entiende surtida al finalizar el día siguiente al de la entrega del aviso."] },
  { id: "ley2213_notificacion_electronica", nombre: "Notificación personal por mensaje de datos (perfeccionamiento)", tipo: "NOTIFICACION", areas: ["CIVIL", "COMERCIAL", "FAMILIA", "LABORAL", "ADMINISTRATIVO"], unidad: "DIAS_HABILES", cantidad: 2, inicio: "Envío del mensaje de datos", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Ley 2213 de 2022, art. 8", url: `${SENADO}/ley_2213_2022.html`, verificacion: "CONTRASTADA (art. 8 Ley 2213 de 2022, Secretaría del Senado)", notas: ["Los términos empiezan a correr a partir del día siguiente; cuando hay acuse de recibo o se constata el acceso, debe calcularse también esa fecha y tomarse la más conservadora."] },
  { id: "ley2213_traslado_canal_digital", nombre: "Traslado por canal digital sin intervención de secretaría", tipo: "NOTIFICACION", areas: ["CIVIL", "COMERCIAL", "FAMILIA", "LABORAL"], unidad: "DIAS_HABILES", cantidad: 2, inicio: "Envío del escrito a los demás sujetos procesales", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Ley 2213 de 2022, art. 9, parágrafo", url: `${SENADO}/ley_2213_2022.html`, verificacion: "PENDIENTE de verificación en fuente oficial" },
  // ─── Laboral procesal
  { id: "cptss_contestacion", nombre: "Traslado de la demanda laboral ordinaria", tipo: "PROCESAL", areas: ["LABORAL", "SEGURIDAD_SOCIAL"], unidad: "DIAS_HABILES", cantidad: 10, inicio: "Notificación del auto admisorio", inicioCuenta: "DIA_SIGUIENTE", calendario: "JUDICIAL", norma: "Código Procesal del Trabajo y de la Seguridad Social, art. 74", url: `${SENADO}/codigo_procedimental_laboral.html`, verificacion: "PENDIENTE de verificación en fuente oficial" },
  // ─── Penal y policivo
  { id: "penal_querella", nombre: "Caducidad de la querella", tipo: "CADUCIDAD", areas: ["PENAL"], unidad: "MESES", cantidad: 6, inicio: "Comisión del delito (o conocimiento por causa ajena a la víctima, según la norma)", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Ley 906 de 2004, art. 73", url: `${SENADO}/ley_0906_2004.html`, verificacion: "PENDIENTE de verificación en fuente oficial", deOficio: true },
  { id: "policivo_amparo", nombre: "Caducidad de la acción policiva de protección de bienes inmuebles", tipo: "CADUCIDAD", areas: ["POLICIVO"], unidad: "MESES", cantidad: 4, inicio: "Momento de la perturbación", inicioCuenta: "MISMO_DIA", calendario: "CALENDARIO", norma: "Ley 1801 de 2016, art. 80", url: `${SENADO}/ley_1801_2016.html`, verificacion: "PENDIENTE de verificación en fuente oficial", deOficio: true },
];

export function entradaTermino(id: string): EntradaTermino {
  const e = CATALOGO_TERMINOS.find((t) => t.id === id);
  if (!e) throw new Error(`Término no catalogado: ${id}`);
  return e;
}

export function estaVerificado(e: EntradaTermino): boolean {
  return e.verificacion.startsWith("VERIFICADA") || e.verificacion.startsWith("CONTRASTADA");
}
